--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fairus/wallpapers/Ryo Vending Machine.png"

-- Special
background="#0c0e1a"
foreground="#d9d5dc"
cursor="#d9d5dc"

-- Colors
color0="#0c0e1a"
color1="#4361AD"
color2="#C056B0"
color3="#52A5D5"
color4="#6499E0"
color5="#AD9BA9"
color6="#9CAADD"
color7="#d9d5dc"
color8="#97959a"
color9="#4361AD"
color10="#C056B0"
color11="#52A5D5"
color12="#6499E0"
color13="#AD9BA9"
color14="#9CAADD"
color15="#d9d5dc"
